# -*- coding: utf-8 -*-
"""fetch_epss.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ffgth60P5mrv79-puvCaM_CmSfjLnVbV
"""

import pandas as pd
import requests

def fetch_epss(limit=500):
    # EPSS API 文档: https://api.first.org/data/v1/epss
    url = f"https://api.first.org/data/v1/epss?limit={limit}"
    r = requests.get(url, timeout=30)
    r.raise_for_status()
    js = r.json()
    df = pd.DataFrame(js["data"])
    # 统一字段名与类型
    df = df.rename(columns={"cve": "cve_id", "epss": "epss_score"})
    df["epss_score"] = df["epss_score"].astype(float)
    return df[["cve_id", "epss_score"]]

if __name__ == "__main__":
    df = fetch_epss()
    df.to_csv("epss_raw.csv", index=False)

# df = pd.read_csv("epss_raw.csv")
# print(df.head())  # 显示前几行